export const libKey = [
  "random",
  " pipe",
  " open",
  " close",
  " write",
  " curdir",
  " mkdir",
  " chdir",
  " rmdir",
  " getcwd",
  " remove",
  " rename",
  " seek",
  " tell",
  " strftime",
  " argv",
  " today",
  " version",
  " date",
  " datetime",
  " sys",
  " re",
  " statistics",
  " system",
  " os",
  " and",
  " as",
  " assert",
  " break",
  " class",
  " continue",
  " def",
  " del",
  " elif",
  " else",
  " except",
  " exec",
  " abort",
  " finally",
  " for",
  " from",
  " global",
  " if",
  " import",
  " in",
  " is",
  " lambda",
  " not",
  " or",
  " pass",
  " print",
  " raise",
  " return",
  " try",
  " while",
  " with",
  " yield",
  " bool",
  " numpy",
  " array",
  " await",
  " async",
  " float",
  " str",
  " int",
  " format",
  " range",
  " split",
  " math",
  " strip",
  " rstrip",
  " lstrip",
  " join",
  " append",
  " len",
  " matplotlib",
  " replace",
  " find",
  " insert",
  " remove",
  " sort",
  " count",
  " clear",
  " __main__",
  " __init__",
  " itertools",
  " groupby",
  " shutil",
  " copyfile",
  " move",
  " False",
  " True",
  " None",
  " values",
  " sklearn",
  " pandas",
  "",
];

export const psjUtilKeys = [
  "JPT",
  " Exec",
  " jpt",
  " dwg",
  " ELEMTYPE_PLOT",
  " LBC_NOLIN4",
  " LBC_T_CENTRIFUGAL_FORCE",
  " INST",
  " LBC_FORCE_VECTOR",
  " UpdateSelectors",
  " GetSelectedElemsCr",
  " AS_SOLIDELEM",
  " LBC_WELD",
  " CopyToClipBoard",
  " GetAllPartsInSubAssembly",
  " SHAPELINK",
  " Unit_ThermalExCoef",
  " DeSelectArrayCursor",
  " ABAQUSJOB",
  " GetAppPathInfo",
  " Unit_HeatFlux",
  " ELEMKIND_UNKNOWN",
  " x",
  " DTABLE_CONNECTION",
  " REF_SOLID",
  " CONNECT_MOMENT",
  " Unit_Modulus",
  " AS_CONTTACT",
  " TVector3d",
  " ConvertFromDocUnit",
  " Unit_StrainEnergy",
  " CONNECT_PROD",
  " AddNodeSelector",
  " RemoveAllLoadCases",
  " ADVCJOB",
  " FindSubAssemblyByID",
  " CheckLicense",
  " LBC_MAPPING_TEMP_LOAD",
  " PROPERTY_2D_SHELL",
  " isFloating",
  " DElem",
  " ELEMTYPE_HEX20",
  " LBC_INITSTRESS_GENERAL",
  " ABAQSTEPS_STRUCT_COUPLEDTD",
  " RemoveAllLoadsBCs",
  " colorMesh",
  " parent",
  " Unit_VolumeEnergyDensity",
  " FEM_FIELD_SCALAR",
  " LBC_G_PRESSURE",
  " GetEntitiesByAdjacent",
  " LBC_FORCE_QUADRATIC",
  " DTABLE_LBC_START",
  " Unit_AreaMomentInertia",
  " GetMaxMaterialID",
  " AddBodySelector",
  " Unit_Force",
  " CUSTOM_ATTR_DOUBLE",
  " GetAllByType",
  " Exec",
  " DeleteSubAssemblyRecursively",
  " AS_FACE",
  " DTABLE_UNKNOWN",
  " GetCurrentDocumentPath",
  " DGroup",
  " Unit_Length",
  " LBC_PRETENSION_ABAQUS",
  " AddVertexSelector",
  " CONTACT",
  " DTABLE_CONTACT",
  " REF_FACE",
  " ConvertFromMacroUnit",
  " VersionInfo",
  " CONNECT_WELD",
  " GetSelectedEdges",
  " CONTACT_NXNASTRAN",
  " PY_MACRO_ADDED",
  " LBC_SURFACE_LOADS",
  " ELEMTYPE_PRISM6",
  " ABAQSTEPS",
  " AddGroupSelector",
  " ATTRIBUTE_FXWELD",
  " GetSelectedNodes",
  " id",
  " masters",
  " Unit_Strain",
  " AddElementSelector",
  " LBC_TEMP_LOAD_GENERAL",
  " GroupVector",
  " LBC_GRAVITY",
  " ABAQSTEPS_STRUCT_DYNAMIC_EXPLICIT",
  " ADVCPROCESS_SSH",
  " DFace",
  " DTABLE_LBC_END",
  " GetMinIDEntity",
  " ATTRIBUTE_PS_BLENDSURFACE",
  " AddFacePointSelector",
  " GetAllLoadsBCs",
  " LBC_MAPPING_THERMAL_CONVECTION",
  " LBC_SUBMODEL_FORCED_FLUX",
  " isValid",
  " EdgeVector",
  " Unit_LinearDensity",
  " z",
  " type",
  " PROPERTY_2D_COMPOSITE_SHELL",
  " major",
  " ADVCPROCESS_CREEP",
  " DTABLE_COORDINATE",
  " IsDefaultInt",
  " Unit_Energy",
  " ELEMKIND_2D",
  " TEMP_PATH",
  " AS_ELEM1D",
  " LBC_DOFSET",
  " Show",
  " CUSTOM_ATTR_STRING",
  " LBC_MAPPING_FORCEDDISPLACEMENT",
  " ANSYSJOB",
  " LBC_TEMP_LOAD_ADVC_RESULT_REFERENCE",
  " LBC_MAPPING_HEATFLUX",
  " LBC_TEMP_LOAD",
  " ELEMTYPE_UNKNOWN",
  " ELEMTYPE_TRI6",
  " SelectDlgComboBox",
  " AddCoordinateSelector",
  " ELEMEDGE_GROUP",
  " ELEMTYPE_HEX8",
  " VERTEX",
  " PROPERTY_3D_WELDBEAD",
  " ELEMTYPE_TRI3",
  " LBC_MAPPING_FORCE",
  " ELEMTYPE_PRISM15",
  " Unit_ThermalConductivity",
  " LSDYNAJOB",
  " AddFaceSelector",
  " Unit_Time",
  " Hide",
  " RemoveEntitiesByID",
  " LBC_INSIDE_HEAT_GENERATION",
  " RemoveAllFieldTables",
  " GetJTDBVersion",
  " GetAllSelected",
  " name",
  " Unit_Mass",
  " DYANAMISJOB",
  " RemoveAllAbaqusStep",
  " DTABLE_SHAPE",
  " ELEMTYPE_QUAD8",
  " ADVCPROCESS_RESP_SPEC",
  " Unit_Volume",
  " SelectArrayCursor",
  " AS_EDGE",
  " GetSelectedParts",
  " ABAQSTEPS_THERMAL_TRANSIENT",
  " ELEMTYPE_MASS",
  " ABAQSTEPS_THERMAL_SS",
  " COORD",
  " ELEMKIND_3D",
  " GetEntitiesByID",
  " END",
  " ConvertValueToMacroUnit",
  " ELEMTYPE_TET4",
  " CONNECT_BUSH",
  " AddPyObserver",
  " ELEMTYPE_QUAD9",
  " DItemVector",
  " DItem",
  " UnitType",
  " children",
  " GetRedoCount",
  " InverseHideBodies",
  " GetLastCreatedCursor",
  " ADVCPROCESS_MODAL_FREQ_RESP",
  " ELEMTYPE_POINT",
  " CONNECT_CONM",
  " GetMaterialDBById",
  " nodes",
  " ElemKind",
  " BODYLINK",
  " LBC_CONTACT_CLEARANCE",
  " CONNECT_RBE2",
  " DTABLE_BODY",
  " ELEMTYPE_PRISM12",
  " RemoveAllByTableType",
  " GetOpnList",
  " ELEMKIND_0D",
  " LBC_MAPPING_TEMP_BOUNDARY",
  " CONTACT_ADVC",
  " DTABLE_LSDYNAJOB",
  " LBC_MAPPING_FORCED_TEMP",
  " ABAQSTEPS_STRUCT",
  " Unit_LinearMassMomentIntertia",
  " BodyVector",
  " slaves",
  " PROJECT",
  " PROPERTY_1D_ROD",
  " LBC_SUBMODEL_FORCED_DISP",
  " LBC_TEMP_LOAD_NASTRAN",
  " Unit_Pressure",
  " ELEMTYPE_TET10",
  " GetAllEdges",
  " DTABLE_ELEM",
  " CONNECT_GAP",
  " Apply",
  " ELEMTYPE_HEX18",
  " REF_ELEM",
  " y",
  " GetMaxIDEntity",
  " SOLID",
  " CONNECT_RBAR",
  " GetSelectedGroups",
  " Unit_SurfaceDensity",
  " typeID",
  " GetUndoCount",
  " GetMacroLog",
  " GetPythonAPILog",
  " Add1DElementSelector",
  " IsDefaultDouble",
  " LBC_MAPPING_PRESSURE",
  " SetDlgText",
  " ADVCPROCESS_DYNAMIC_EXPLICIT",
  " REF_SHAPELINK",
  " PROPERTY_1D_BAR",
  " ADVCPROCESS_FATIGUE",
  " PROPERTY_3D_COHESIVE",
  " ClearRedo",
  " GetAllNodes",
  " AS_BODY",
  " AS_MASS",
  " ABAQSTEPS_STRUCT_FREQUENCY",
  " targets",
  " ELEMTYPE_VIRTUAL",
  " LBC_FORCE",
  " WELDORDER",
  " ELEMTYPE_PYRAMID13",
  " LBC_SUBMODEL_FORCED_TEMP",
  " DTABLE_NODE",
  " DTABLE_DYNAMISJOB",
  " LBC_CONSTRAINT",
  " CONNECT_DAMPER",
  " ABAQSTEPS_THERMAL",
  " DTABLE_ANSYSJOB",
  " LBC_TEMP_INI",
  " SUP_GROUP",
  " LBC_TEMP_BOUNDARY",
  " GetCenterOfEntities",
  " DEdge",
  " FALSE_VAL",
  " ADVCPROCESS_TH",
  " RemoveAllContacts",
  " BEAM_PROP_ATTR",
  " ConvertValueToDocUnit",
  " ELEMTYPE_RBE",
  " AddConditionSelector",
  " REF_VERTEX",
  " elems",
  " Unit_Acceleration",
  " PushDlgButton",
  " Notify",
  " DTABLE_ABAQUSJOB",
  " DTABLE_FIELD_DATA",
  " DTABLE_LOCAL_SETTING",
  " SelectionListDlg",
  " DTableType",
  " LBC_CONCENTRATE_FLUX",
  " RemoveAllMeshSettings",
  " LBC_PRETENSION",
  " Unit_ConvectionCoef",
  " ADVCPROCESS_STATIC",
  " ENTITY_ATTR_CAD_INFO",
  " LBC_TEMP_LOAD_ADVC_FILE",
  " LBC_ENFORCED_ACCELERATION",
  " NASTRANJOB",
  " RemoveAllCoordinates",
  " RemovePyObserver",
  " DTABLE_ACTRANJOB",
  " Unit_Moment",
  " ADVCPROCESS_RAND_RESP",
  " edges",
  " Unit_RotateVelo",
  " LBC_THERMAL_CONVECTION",
  " PROPERTY_0D_MASS",
  " RemoveAllMaterials",
  " CONTACT_MSCNASTRAN",
  " Unit_TorsionalConst",
  " LBC_INITSTRESS_MAPPING",
  " Unit_RotateAcc",
  " SECTION_LIBRARY",
  " NASTRAN_POSTJOB",
  " GetEntitiesByAssociation",
  " AddEdgeSelector",
  " CreateSubAssembly",
  " GetAllFaces",
  " LBC_FORCE_SINE",
  " Create",
  " ElemVector",
  " vertexs",
  " CONN_PROP_ATTR",
  " AssociateType",
  " BARBODY",
  " CONNECT_MPC",
  " sub",
  " Unit_Density",
  " LBC_PRETENSION_NXN",
  " GetAllGroups",
  " LBC_NOLIN3",
  " QuitApplication",
  " ShowHideEntitiesByID",
  " GetMaterialOriginalXML",
  " GetSelectedPartsCr",
  " GetSelectedNodesCr",
  " USER_PROP",
  " ELEMTYPE_QUAD6",
  " DoubleVector",
  " ViewFitToModel",
  " LBC_PRESSURE_SINE",
  " EntityType",
  " DItemType",
  " Unit_Velocity",
  " REF_EDGE",
  " minor",
  " GetSelectedFacesCr",
  " BoolType",
  " Unit_Temperature",
  " LBC_PRESSURE_QUADRATIC",
  " AddBarBodySelector",
  " AS_GROUP",
  " Unit_Stress",
  " ClearUndo",
  " DTABLE_ADVCPROCESS",
  " AddEdgePointSelector",
  " APPDATA_PATH",
  " CONTACT_ABAQUS",
  " LBC_ENFORCED_DISP",
  " FindSubAssemblyByName",
  " FEM_FIELD_VECTOR",
  " ADVCPROCESS",
  " DTABLE_LOADCASE",
  " GetEntitiesByPosition",
  " NCS",
  " Unit_Area",
  " CONNECTION_ELEMENT",
  " Unit_Angle",
  " PROPERTY_1D_PLOT",
  " LBC_CS_CENTRIFUGAL_FORCE",
  " GetAllParts",
  " CONNECT_SPRING",
  " LBC_INIT_ANGULAR_VEL_ABAQUS",
  " RemoveWSProperties",
  " ELEMTYPE_LINE2",
  " ShowHideAllParts",
  " AS_ELEM",
  " DTABLE_ABAQSTEPS",
  " Unit_WarpCoef",
  " DeleteSubAssembly",
  " ConvertRGBToJPTColor",
  " ABAQSTEPS_STRUCT_DYNAMIC_COUPLEDTD",
  " GetProgramPath",
  " ReadJTDBVersion",
  " ELEMTYPE_LINE3",
  " AS_CONNECTION",
  " TRUE_VAL",
  " GetSharedFaces",
  " LBC_MAPPING_TEMP_INIT",
  " LBC_FORCE_ND",
  " PyNotificationType",
  " GetAllByTableTypeID",
  " CONNECT_CONNECTOR",
  " ACTRANJOB",
  " GetSelectedGroupsCr",
  " DNode",
  " pos",
  " Unit_Power",
  " DOC_PATH",
  " GetCountByType",
  " FEM_FIELD_TENSOR",
  " PY_DOCUMENT_SWITCHED",
  " ADVCPROCESS_DYNAMIC",
  " LBC_NOLIN1",
  " DBody",
  " DTABLE_ADVCJOB",
  " REF_BODYLINK",
  " ELEMTYPE_QUAD4",
  " DTABLE_PROPERTY",
  " kind",
  " ABAQSTEPS_STRUCT_STATICRISK",
  " DTABLE_MATERIAL",
  " Unit_DampingCoef",
  " ADVC2_POSTJOB",
  " StringVector",
  " SHELL_PROP_ATTR",
  " Unit_MomentInertia",
  " UNKNOWN",
  " RemoveAllSolverjob",
  " GetJPTTempPath",
  " LBC_ENFORCED_VELOCITY",
  " RemoveAllConnections",
  " REF_NODE",
  " SECTION_SKETCHER",
  " GetAllElems",
  " ADVCPROCESS_EIGEN",
  " key",
  " RemoveEntitiesByName",
  " faces",
  " transparency",
  " LBC_T_PRESSURE",
  " GetSharedElements",
  " Unit_Frequency",
  " LBC_DYNAMIC_INITIAL_CONDITION",
  " PROPERTY_1D_BEAM",
  " Cancel",
  " ABAQSTEPS_STRUCT_DYNAMIC",
  " GetSharedNodes",
  " Destroy",
  " ABAQSTEPS_STRUCT_STATIC",
  " SECTION_GENERAL",
  " NodeVector",
  " CONNECT_RBE3",
  " GetSelectedFaces",
  " PROPERTY_3D_SOLID",
  " Unit_ElectricalResistivity",
  " PrintAppPathInfo",
  " AddSolidElementSelector",
  " AddElementEdgeSelector",
  " REF_BODY",
  " Unit_RotateDampingCoef",
  " GetEntitiesByName",
  " color",
  " PROPERTY_3D_GASKET",
  " LBC_H_PRESSURE",
  " GetSelectedElems",
  " FaceVector",
  " BEAM_PROP_ATTR2",
  " LOADCASE",
  " Unit_HeatGeneration",
  " CONTACT_ANSYS",
  " PathType",
  " ELEMTYPE_PYRAMID5",
  " DCS",
  " GetSelectedEdgesCr",
  " MATERIAL",
  " ElemType",
  " CONTACT_TSSS",
  " ELEMKIND_1D",
  " LBC_MAPPING_TEMP_MARINE_ENGINE",
  " LBC_SURFACE_FLUX",
  " Unit_ThermalEnergy",
  " GetAllByTypeID",
  " LBC_RIGIDWALL",
  " info",
  " Unit_RotateStiff",
  " Unit_SpecificHeat",
  " build",
  " MsgOut",
  " DTABLE_GROUP",
  " BODY",
  " ELEMKIND_SP",
  " GetMaterialXML",
  " AS_NODE",
  " CUSTOM_ATTR_VECTOR",
  " LOCAL_SETTING",
  " DTABLE_NASTRANJOB",
  " Unit_Stiffness",
  " PROGRAM_PATH",
  " ClearPyObserver",
  " NODE",
  " EDGE",
  " FACE",
  " ELEM",
  " GROUP",
  " Debugger",
  " PrintPSJUtilityManual",
  " CastDItemToDBody",
  " CastDItemToDFace",
  " CastDItemToDElem",
  " CastDItemToDEdge",
  " CastDItemToDGroup",
  " CastDItemToDNode",
  " GetElemsByKind",
  " GetRandomJPTColor",
  " ConvertJPTColorToRGB",
  " ClearLog",
  " CastToDItem",
  " DItemToMacroTCursorPair",
  " ListDoubleToMacroVector",
  " DTVector3dToMacroVector",
  " DItemToMacroTCursor",
  " DItemListToMacroListTCursor",
  " DItemToMacroListTCursor",
  " MacroResultParser",
  " MacroListTCursorToListDItem",
  " MacroTCursorToDItem",
  " sizeVec",
  " clearVec",
  " addObj",
  " extendVec",
  " deleteObj",
  " isContainObj",
  " SetSelectMethod",
  " SELMTD_NONE",
  " SELMTD_BODY",
  " SELMTD_BAR_BODY",
  " SELMTD_FACE",
  " SELMTD_EDGE",
  " SELMTD_VERTEX",
  " SELMTD_SOLIDELEM",
  " SELMTD_ELEM",
  " SELMTD_ELEM1D",
  " SELMTD_ELEM_EDGE",
  " SELMTD_NODE",
  " SELMTD_CONDITION",
  " SELMTD_COORDINATE",
  " SELMTD_GROUP",
  " SELMTD_PROPERTY",
  " SELMTD_FACE_POINT",
  " SELMTD_EDGE_POINT",
  " SELMTD_VIEW_ITEM",
  " SELMTD_CONDITION_MPC",
  " SELMTD_CONDITION_RBE2",
  " SELMTD_CONDITION_RBE3",
  " SELMTD_CONDITION_RBAR",
  " SELMTD_CONDITION_SPRING",
  " SELMTD_CONDITION_MASS",
  " SELMTD_CONDITION_CONNECTOR",
  " SELMTD_CONDITION_PRESSURE",
  " SELMTD_CONDITION_FORCE",
  " SELMTD_CONDITION_ENFORCE",
  " SELMTD_CONDITION_CONSTRAIN",
  " SELMTD_CONDITION_TEMP",
  " SELMTD_SOLID_TET4",
  " SELMTD_SOLID_TET10",
  " SELMTD_SOLID_HEX8",
  " SELMTD_SOLID_HEX20",
  " SELMTD_SOLID_PENT6",
  " SELMTD_SOLID_PEN15",
  " SELMTD_SOLID_PYRD5",
  " SELMTD_SOLID_PYR13",
  " SELMTD_SHELL_TRI3",
  " SELMTD_SHELL_TRI6",
  " SELMTD_SHELL_QUAD4",
  " SELMTD_SHELL_QUAD8",
  " SelectMethodType",
  " DItemPair",
  " DItemPairVector",
  " MacroTCursorPairToDItemPair",
  " MacroListTCursorPairToListDItemPair",
  " MB_WARNING_YESNOCANCEL",
  " MB_WARNING_YESNO",
  " MB_WARNING_OK",
  " MB_WARNING_OKCANCEL",
  " MB_INFORMATION_YESNOCANCEL",
  " MB_INFORMATION_YESNO",
  " MB_INFORMATION_OK",
  " MB_INFORMATION_OKCANCEL",
  " MsgBoxType",
  " MessageBoxPSJ",
  " GetFirstDItem",
  " GetSecondDItem",
  "",
];

export const psjGuiKeys = [
  "pyjdg",
  " dlg",
  " generate_window",
  " add_button",
  " add_textbox",
  " add_label",
  " add_imagectrl",
  " on_command",
  "add_combobox_option",
  " add_space",
  " add_combobox",
  " set_image_file",
  " add_textbox",
  " add_hlayout",
  " add_groupbox ",
  "add_vlayout",
  " do_modal",
  " JDGCreator",
  "",
];

export const root1 = [
  "Export",
  "FileMenu",
  "HGTMufflerModeling",
  "ImportCAD",
  "ImportMesh",
  "Utility",
  "ACModeling",
  "Analysis",
  "Assemble",
  "Assembly",
  "BoundaryConditions",
  "Connections",
  "Designer",
  "EngReliability",
  "ExManifoldModeling",
  "Geometry",
  "Groups",
  "HexModeling",
  "Home",
  "MainWindow",
  "MeshCleanup",
  "MeshEdit",
  "Meshing",
  "MidPlane",
  "MidPlaneEdit",
  "MMCCarACTools",
  "MufflerHA",
  "MufflerT",
  "MuxWeld",
  "NSModeling",
  "OasisAWizard",
  "Post",
  "Properties",
  "SNOnePush",
  "StiffCalc",
  "SZOnepushReliability",
  "Test",
  "Tool",
  "Toolbar",
  "Tools",
];

export const root2 = [
  "STL",
  "AddJTDB",
  "Save",
  "LoadDB",
  "CreateBeadWeld",
  "Spatial",
  "TechnoStarGeometry",
  "CreoDirect",
  "Elysium",
  "NastranBdf",
  "AbaqusINP",
  "LSDYNA",
  "ADVCADX",
  "Universal",
  "AnsysDat",
  "TSVPre",
  "FindEntities",
  "MeasureDistanceBy2Edges",
  "ACBoundary",
  "Create",
  "CloseHoleAuto",
  "Cut",
  "AbaqusStep",
  "ACTRAN",
  "Analysis",
  "Ansys",
  "Nastran",
  "Permas",
  "TSSolver",
  "TSSS",
  "Abaqus",
  "ExportAnsys",
  "ExportAbaqus",
  "ModifyLbcToStep",
  "ExportAdx",
  "ExportLsdyna",
  "NastranJob",
  "LSDYNAJob",
  "ADVC",
  "SeparateFaces",
  "Boolean",
  "AssembleFace",
  "FullLayer",
  "CylinderLayer",
  "SharedFace",
  "AssembleFaces",
  "GeneralLayer",
  "AddRib",
  "FindMatingFace",
  "AddBoss",
  "RightClick",
  "BoundaryTemperature",
  "Convection",
  "EnforcedLoads",
  "HeatFlux",
  "InitialElementalValue",
  "InitialTemperature",
  "LBCCopy",
  "Pressure",
  "Submodel",
  "TemperatureLoads",
  "LoadCase",
  "InsideHeatGeneration",
  "LbcContactConvert",
  "FieldData",
  "FixedConstraint",
  "DofSet",
  "BodyLoads",
  "Force",
  "InitialNodalValue",
  "Pretension",
  "MassElements",
  "BarBeam",
  "Gaps",
  "Plot",
  "CreateConnConm",
  "RBE3",
  "RigidWall",
  "Connector",
  "BoltMeshing_SplitOnly",
  "BoltMeshing_NotSplitOnly",
  "BoltConnections",
  "Contacts",
  "MPC",
  "RigidElements",
  "SpringsDampers",
  "LBC",
  "Load",
  "FindContact",
  "ContactMerge",
  "Material",
  "SubModelBC",
  "SZ",
  "Bar",
  "BodyCut",
  "BreakEntity",
  "DeleteEntity",
  "Edge",
  "Extract",
  "ExtractSurfaces",
  "Face",
  "FindFeature",
  "MergeEntities",
  "Part",
  "ShowAdjacent",
  "Transform",
  "CADTrim",
  "CreateBar",
  "StitchEdge",
  "LogoRemoval",
  "ShellAsm",
  "SquareUpFillet",
  "MakeFillet",
  "MakeFacePlanar",
  "FCircleAdjustVertex",
  "AdjustHalfCylinder",
  "FCircVertexAdjust",
  "RemoveRibBoss",
  "AdvancedShellAssembly",
  "Sweep",
  "SolidElemInterface",
  "BallHexa",
  "BoxMesh",
  "AutoSweep",
  "Circular",
  "FaceToFace",
  "Layer",
  "Linear",
  "FromMidPlane",
  "Curve",
  "ImportCAD",
  "ImportMesh",
  "Export",
  "ToImage",
  "Find",
  "RectangularCapture",
  "CopyToClipboard",
  "FullScreen",
  "Synchronize",
  "Element",
  "CorrectModel",
  "CloseHoles",
  "CloseGap",
  "AutoCheck",
  "ManualCheck",
  "ChangeTopology",
  "Cleanup",
  "Manual2D",
  "Manual3D",
  "CreateElement",
  "CreateNode",
  "MoveNode",
  "ElementConvert",
  "Deform",
  "MirrorCopy",
  "DeleteNode",
  "FaceImprint",
  "AdjustOrientation",
  "OneNode",
  "SeparateNodes",
  "RefineQuality",
  "Import",
  "RemoveSolidMesh",
  "MeshEditCMPMeshCopy",
  "MeshEditMorphingRibThickness",
  "MergeNodes",
  "MeshCopy",
  "RibThickness",
  "ChangePattern",
  "SurfaceMesh",
  "SolidMesh",
  "CADProjection",
  "LocalMeshing",
  "LocalSetting",
  "Templates",
  "BarMeshing",
  "GridMesh",
  "SolidMeshing",
  "SurfaceMeshing",
  "SetAttib",
  "LocalRemesh",
  "LocalSettings",
  "AdjustThickness",
  "FaceCross",
  "CreateThickProps",
  "FindMidPlane",
  "ExtendFace",
  "Manual",
  "AddItems",
  "ACModelCreationTools",
  "ClearanceElement",
  "CreateEdge",
  "CreateEdgeClassic",
  "CopyMeshCount",
  "SpecialModeling",
  "CreateWeld",
  "DefineSequence",
  "MeshingPass",
  "Prop3DWeldBead",
  "NSModeling_Close_Hole",
  "ImportResults",
  "ElemRelatedInfo",
  "Section",
  "Cohesive",
  "Gasket",
  "Shell",
  "PropertyTable",
  "Beam",
  "Rod",
  "Property1DBeamSimple",
  "Solid",
  "Section1D",
  "Composite",
  "BAR",
  "ThicknessDistribution",
  "RigidBody",
  "DropTest",
  "CADImport",
  "AutoSweepClosedLoopShaped",
  "Assembly",
  "MeshEdit",
  "AlignMidNode",
  "Connection",
  "MeshQuality",
  "Muffler",
  "ZGeometryTest",
  "FindFeatureFillet",
  "FindFacesInPart",
  "CreateElementForWelding",
  "Connections",
  "Coordinates",
  "Group",
  "ImprintEdges",
  "ElementCS",
  "Measure",
  "Undo",
  "Redo",
  "BySelection",
  "TotalLoad",
  "NodeCS",
  "NodeCSGroup",
  "DisplacementCS",
  "GroupByDCS",
  "Renumber",
  "RenumberByConnection",
  "RenumberByFile",
  "ModelInfo",
];

export const map12 = {
  Export: ["STL"],
  FileMenu: ["AddJTDB", "Save", "LoadDB"],
  HGTMufflerModeling: ["CreateBeadWeld"],
  ImportCAD: ["Spatial", "TechnoStarGeometry", "CreoDirect", "Elysium"],
  ImportMesh: [
    "NastranBdf",
    "AbaqusINP",
    "LSDYNA",
    "ADVCADX",
    "Universal",
    "AnsysDat",
    "TSVPre",
  ],
  Utility: ["FindEntities", "MeasureDistanceBy2Edges"],
  ACModeling: ["ACBoundary", "Create", "CloseHoleAuto", "Cut"],
  Analysis: [
    "AbaqusStep",
    "ACTRAN",
    "Analysis",
    "Ansys",
    "Nastran",
    "Permas",
    "TSSolver",
    "TSSS",
    "Abaqus",
    "ExportAnsys",
    "ExportAbaqus",
    "ModifyLbcToStep",
    "ExportAdx",
    "ExportLsdyna",
    "NastranJob",
    "LSDYNAJob",
    "ADVC",
  ],
  Assemble: [
    "SeparateFaces",
    "Boolean",
    "AssembleFace",
    "FullLayer",
    "CylinderLayer",
    "SharedFace",
    "AssembleFaces",
    "GeneralLayer",
    "AddRib",
    "FindMatingFace",
    "AddBoss",
  ],
  Assembly: ["RightClick"],
  BoundaryConditions: [
    "BoundaryTemperature",
    "Convection",
    "EnforcedLoads",
    "HeatFlux",
    "InitialElementalValue",
    "InitialTemperature",
    "LBCCopy",
    "Pressure",
    "Submodel",
    "TemperatureLoads",
    "LoadCase",
    "InsideHeatGeneration",
    "LbcContactConvert",
    "FieldData",
    "FixedConstraint",
    "DofSet",
    "BodyLoads",
    "Force",
    "InitialNodalValue",
  ],
  Connections: [
    "Pretension",
    "MassElements",
    "BarBeam",
    "Gaps",
    "Plot",
    "CreateConnConm",
    "RBE3",
    "RigidWall",
    "Connector",
    "BoltMeshing_SplitOnly",
    "BoltMeshing_NotSplitOnly",
    "BoltConnections",
    "Contacts",
    "MPC",
    "RigidElements",
    "SpringsDampers",
  ],
  Designer: ["LBC", "Load", "FindContact", "ContactMerge", "Material"],
  EngReliability: ["SubModelBC"],
  ExManifoldModeling: ["SZ"],
  Geometry: [
    "Bar",
    "BodyCut",
    "BreakEntity",
    "DeleteEntity",
    "Edge",
    "Extract",
    "ExtractSurfaces",
    "Face",
    "FindFeature",
    "MergeEntities",
    "Part",
    "ShowAdjacent",
    "Transform",
    "CADTrim",
    "CreateBar",
    "StitchEdge",
    "LogoRemoval",
    "ShellAsm",
    "SquareUpFillet",
    "MakeFillet",
    "MakeFacePlanar",
    "FCircleAdjustVertex",
    "AdjustHalfCylinder",
    "FCircVertexAdjust",
    "RemoveRibBoss",
    "AdvancedShellAssembly",
  ],
  Groups: ["RightClick"],
  HexModeling: [
    "Sweep",
    "SolidElemInterface",
    "BallHexa",
    "BoxMesh",
    "AutoSweep",
    "Circular",
    "FaceToFace",
    "Layer",
    "Linear",
    "FromMidPlane",
    "Curve",
  ],
  Home: [
    "ImportCAD",
    "ImportMesh",
    "Export",
    "ToImage",
    "Find",
    "RectangularCapture",
    "CopyToClipboard",
    "FullScreen",
    "Synchronize",
  ],
  MainWindow: ["RightClick"],
  MeshCleanup: [
    "Element",
    "Face",
    "CorrectModel",
    "CloseHoles",
    "CloseGap",
    "AutoCheck",
    "ManualCheck",
    "ChangeTopology",
    "Cleanup",
    "Manual2D",
    "Manual3D",
  ],
  MeshEdit: [
    "CreateElement",
    "CreateNode",
    "MoveNode",
    "Face",
    "ElementConvert",
    "Deform",
    "MirrorCopy",
    "DeleteNode",
    "FaceImprint",
    "AdjustOrientation",
    "OneNode",
    "SeparateNodes",
    "RefineQuality",
    "Import",
    "RemoveSolidMesh",
    "MeshEditCMPMeshCopy",
    "MeshEditMorphingRibThickness",
    "MergeNodes",
    "MeshCopy",
    "RibThickness",
    "ChangePattern",
    "SurfaceMesh",
    "SolidMesh",
  ],
  Meshing: [
    "CADProjection",
    "LocalMeshing",
    "LocalSetting",
    "Templates",
    "BarMeshing",
    "GridMesh",
    "SolidMeshing",
    "SurfaceMeshing",
    "SetAttib",
    "LocalRemesh",
    "LocalSettings",
  ],
  MidPlane: [
    "AdjustThickness",
    "FaceCross",
    "CreateThickProps",
    "FindMidPlane",
  ],
  MidPlaneEdit: ["Edge", "ExtendFace", "Face", "Manual", "AddItems"],
  MMCCarACTools: ["ACModelCreationTools", "ClearanceElement"],
  MufflerHA: ["CreateEdge", "CreateEdgeClassic", "CopyMeshCount"],
  MufflerT: ["SpecialModeling"],
  MuxWeld: ["CreateWeld", "DefineSequence", "MeshingPass", "Prop3DWeldBead"],
  NSModeling: ["NSModeling_Close_Hole"],
  OasisAWizard: ["LocalMeshing"],
  Post: ["ImportResults"],
  Properties: [
    "ElemRelatedInfo",
    "Material",
    "Section",
    "Cohesive",
    "Gasket",
    "Shell",
    "PropertyTable",
    "Beam",
    "Rod",
    "Property1DBeamSimple",
    "Solid",
    "Section1D",
    "Composite",
    "BAR",
    "ThicknessDistribution",
    "RigidBody",
  ],
  SNOnePush: ["DropTest", "CADImport", "AutoSweepClosedLoopShaped"],
  StiffCalc: ["Force"],
  SZOnepushReliability: ["Assembly", "MeshEdit", "AlignMidNode"],
  Test: [
    "Connection",
    "MeshQuality",
    "Muffler",
    "ZGeometryTest",
    "FindFeatureFillet",
    "FindFacesInPart",
    "CreateElementForWelding",
  ],
  Tool: [
    "Connections",
    "Coordinates",
    "Group",
    "ImprintEdges",
    "ElementCS",
    "Measure",
    "MeshQuality",
  ],
  Toolbar: ["Undo", "Redo"],
  Tools: [
    "BySelection",
    "Group",
    "TotalLoad",
    "NodeCS",
    "NodeCSGroup",
    "DisplacementCS",
    "Connections",
    "GroupByDCS",
    "Renumber",
    "RenumberByConnection",
    "RenumberByFile",
    "ModelInfo",
    "Section",
    "Measure",
  ],
};

export const map23 = {
  STL: [null],
  AddJTDB: [null],
  Save: [null],
  LoadDB: [null],
  CreateBeadWeld: [null],
  Spatial: [null],
  TechnoStarGeometry: [null],
  CreoDirect: [null],
  Elysium: [null],
  NastranBdf: [null],
  AbaqusINP: [null],
  LSDYNA: [null],
  ADVCADX: [null],
  Universal: [null],
  AnsysDat: [null],
  TSVPre: [null],
  FindEntities: [null],
  MeasureDistanceBy2Edges: [null],
  ACBoundary: ["Method1"],
  Create: ["Convex"],
  CloseHoleAuto: [null],
  Cut: [null],
  AbaqusStep: [
    "DynamicStep",
    "TransientStep",
    "DynamicCoupledTDExplicitStep",
    "CoupledTDStep",
    "DynamicExplicitStep",
    "ModalStep",
    "StaticRiskStep",
    "SteadyStateStep",
  ],
  ACTRAN: ["ExportBdf", "Run", "CreateEdat"],
  Analysis: ["Abaqus", "AbaqusSteadyStateStep", "AbaqusStaticRiskStep"],
  Ansys: [
    "HeadTransferSteady",
    "LinearStatic",
    "NormalModes",
    "Harmonic",
    "Steady",
  ],
  Nastran: [
    "ModalTransientResponse",
    "LinearBuckling",
    "Transient",
    "SteadyState",
    "ModalFrequencyResponse",
    "LinearStatic",
    "NormalModes",
  ],
  Permas: ["Job"],
  TSSolver: [
    "ExportDynamisBdf",
    "Job",
    "LinearBucking",
    "LinearStatic",
    "NonlinearStatic",
    "NormalModes",
    "NonlinearFrequency",
    "ModalTransientResponse",
    "TransientHeatTransfer",
    "ModalFrequencyResponse",
    "SteadyStateHeatTransfer",
  ],
  TSSS: [
    "TransientHeatTransfer",
    "LinearStatic",
    "NonlinearStatic",
    "NormalModes",
    "LinearBuckling",
    "ModalFrequencyResponse",
    "SteadyStateHeatTransfer",
  ],
  Abaqus: [null],
  ExportAnsys: [null],
  ExportAbaqus: [null],
  ModifyLbcToStep: [null],
  ExportAdx: [null],
  ExportLsdyna: [null],
  NastranJob: [null],
  LSDYNAJob: [null],
  ADVC: ["MakeProcess", "Structure", "HeatTransfer"],
  SeparateFaces: ["AllSharedNodes", "Shell", "Solid"],
  Boolean: [null],
  AssembleFace: [null],
  FullLayer: [null],
  CylinderLayer: [null],
  SharedFace: [null],
  AssembleFaces: [null],
  GeneralLayer: [null],
  AddRib: [null],
  FindMatingFace: [null],
  AddBoss: [null],
  RightClick: [
    "AddToReference",
    "Suppress",
    "UnSuppress",
    "RestoreOriginalPart",
    "Rename",
    "ChangeEntityColor",
    "AddSubAssembly",
    "ChangeBodyColor",
    "ChangeMeshLineColor",
    "PropertyGroup",
    "DeleteGroup",
    "CopyGroup",
    "AddSupGroup",
    "CreateMatGroup",
    "MergeFaces",
    "SelectAllParts",
    "AssociatedPick",
    "FlipElement",
  ],
  BoundaryTemperature: ["Constant", "SurfaceMapping"],
  Convection: ["Constant", "SurfaceMapping"],
  EnforcedLoads: ["Acceleration", "Velocity", "Displacement"],
  HeatFlux: ["SurfaceFlux", "SurfaceMapping", "ConcentrateFlux"],
  InitialElementalValue: ["InitialStress"],
  InitialTemperature: ["WholeMapping", "Constant", "ADVC", "NastranPunch"],
  LBCCopy: [
    "PropertiesCopyTranslate",
    "PropertiesCopyRotate",
    "PropertiesCopyMirror",
    "ConnectionCopyTranslate",
    "ConnectionCopyRotate",
    "ConnectionCopyMirror",
    "GroupCopyTranslate",
    "GroupCopyRotate",
    "GroupCopyMirror",
    "LBCCopyTranslate",
    "LBCCopyRotate",
    "LBCCopyMirror",
    null,
  ],
  Pressure: [
    "SurfaceLoads",
    "By2Nodes",
    "General",
    "Quadratic",
    "FunctionLoadToCylinder_Sine",
    "SerfaceMapping",
    "Hydrostatic",
    "SurfaceMapping",
  ],
  Submodel: ["SubmodelForcedFlux", "ForcedTempertature", "ForcedDisplacement"],
  TemperatureLoads: [
    "Constant",
    "ADVCFile",
    "NastranPunch",
    "WholeMapping",
    "LbcInitialTemperature",
  ],
  LoadCase: [null],
  InsideHeatGeneration: [null],
  LbcContactConvert: [null],
  FieldData: [null],
  FixedConstraint: [null],
  DofSet: [null],
  BodyLoads: ["CentrifugalForce", "Gravity"],
  Force: [
    "FunctionLoadCylinder",
    "NonlinearForce",
    "General",
    "FunctionLoadToCylinder_Sine",
    "ForceNormalDirection",
    "FunctionLoadToCylinder_Quadratic",
    null,
  ],
  InitialNodalValue: [
    "InitialAngularVelocity",
    "Displacement",
    "Velocity",
    "RotationAngle",
  ],
  Pretension: ["General", "Abaqus", "Advc"],
  MassElements: [null],
  BarBeam: [null],
  Gaps: [null, "TwoNodes", "TwoEdges", "TwoFaces"],
  Plot: [null],
  CreateConnConm: [null],
  RBE3: [null],
  RigidWall: [null],
  Connector: [null],
  BoltMeshing_SplitOnly: [null],
  BoltMeshing_NotSplitOnly: [null],
  BoltConnections: ["Edge", "Face"],
  Contacts: [
    "Abaqus",
    "ADVC",
    "Ansys",
    "MSCNastran",
    "NXNastran",
    "TSSolver",
    "TSSS",
    "CheckPattern",
    "ExportCheckReport",
  ],
  MPC: ["Equation", "General"],
  RigidElements: ["RBar", "RBE2", "RBE3"],
  SpringsDampers: ["Damper", "Bush", "Spring"],
  LBC: ["Moment", "TemperatureLoad"],
  Load: ["Moment"],
  FindContact: [null],
  ContactMerge: [null],
  Material: [null, "add", "modify", "delete"],
  SubModelBC: [null],
  SZ: ["WeldLine2"],
  Bar: ["TwoNodes", "Arc", "Spline"],
  BodyCut: ["XXYYOnOnePoint", "BySurface", "By3Points"],
  BreakEntity: ["StlPart", "Face", "Edge", "Part"],
  DeleteEntity: ["Part", "Edge", "Face", "Vertex"],
  Edge: [
    "Line",
    "Spline",
    "PlanarLine",
    "Circle",
    "PerpendicularLineOfEdge",
    "ExtendLine",
    "ElementEdges",
    "Angle",
    "NodeShortestPath",
    "OffsetLine",
    "Intersection_Line",
    "Projection_Line",
    "SplineFreeEdges",
    "ClosedLine",
    "PerpendicularCylinderLine",
    "IntersectionLine",
    "ProjectLine",
    "PerpendicularLineToEdge",
    "Nodes",
  ],
  Extract: ["FindFeatureFillet"],
  ExtractSurfaces: ["ExtractRefSurface", "ExtractSurfaces", null],
  Face: [
    "CreateFaceByElem",
    "FourEdges",
    "FromMesh",
    "CreateFaceFromEdges",
    "CreateSmoothFace",
    "Edges",
    "Elements",
    null,
    "FaceExtendtoFace",
    "FaceExtendToIntersection",
    "EdgesToEdges",
  ],
  FindFeature: ["DelCircChamfer", "Fillet", "Faces", "Edges"],
  MergeEntities: [
    "Faces",
    "TinyFacesMerge",
    "CBarParts",
    "Edges",
    "Parts",
    "PartFaces",
  ],
  Part: [
    "Cube",
    "Wedge",
    "Sphere",
    "Torus",
    "Elems",
    "Cylinder",
    "Tube",
    "Trapezoid",
    "Cone",
  ],
  ShowAdjacent: ["Faces", "Elements"],
  Transform: [
    "Rotation",
    "Scaling",
    "Mirror",
    "Position",
    "Translation",
    "MatingFace",
    "CylinderFace",
  ],
  CADTrim: [null],
  CreateBar: [null],
  StitchEdge: [null],
  LogoRemoval: [null],
  ShellAsm: [null],
  SquareUpFillet: [null],
  MakeFillet: [null],
  MakeFacePlanar: [null],
  FCircleAdjustVertex: [null],
  AdjustHalfCylinder: [null],
  FCircVertexAdjust: [null],
  RemoveRibBoss: [null],
  AdvancedShellAssembly: [null],
  Sweep: ["Circular", "FaceToFace", "Layer", "Linear", "Curve", "FromMidPlane"],
  SolidElemInterface: [null],
  BallHexa: [null],
  BoxMesh: [null],
  AutoSweep: [null],
  Circular: [null],
  FaceToFace: [null],
  Layer: [null],
  Linear: [null],
  FromMidPlane: [null],
  Curve: [null],
  ImportCAD: [
    "Elysium",
    "Spatial",
    "Parasolid",
    "STL",
    "VRML",
    "ProECreoDirect",
  ],
  ImportMesh: [
    "ADVCADX",
    "AnsysDat",
    "NastranBdf",
    "AbaqusINP",
    "LSDYNA",
    "Universal",
  ],
  Export: [null],
  ToImage: [null],
  Find: [null],
  RectangularCapture: [null],
  CopyToClipboard: [null],
  FullScreen: [null],
  Synchronize: [null],
  Element: ["SolidElement", "SurfaceElement"],
  CorrectModel: [null],
  CloseHoles: [null],
  CloseGap: [null],
  AutoCheck: [null],
  ManualCheck: [null, "Tri"],
  ChangeTopology: ["Element"],
  Cleanup: ["CloseGap"],
  Manual2D: [
    "MergeElement",
    "SplitElement",
    "Equivalence",
    "DeleteElement",
    "Split",
    "Swap",
    "Collapse",
    "CreateElement",
    "RemeshElement",
  ],
  Manual3D: [
    "Collapse",
    "DeleteNode",
    "Swap",
    "Equivalence",
    "Split",
    "CreateHex",
    "CreatePenta",
    "CreateTetra",
  ],
  CreateElement: ["Hex", "Penta", "Tet", "Tri3", "Quad4", null],
  CreateNode: [
    "CircleCenter",
    "SphereCenter",
    "Absolute",
    "Import",
    "Point",
    "Between2Nodes",
    "Between3Nodes",
    "ProjectToPlane",
    "CreateNodeNodeOffset",
    "CenterOfCylinder",
    "CenterOfSphere",
    "vecOffset",
    "CenterOfGravity",
    "ProjectToLine",
    "IntersectionNode",
  ],
  MoveNode: [
    "Point",
    "ProjectToLine",
    "ProjectToPlaneElem",
    "Equalize",
    "StraightenMidNodes",
    "NormalOffset",
    "CoincidentNodes",
    "AlongCylinder",
    "ProjectToPlane_3Nodes",
    "MoveNodeOffset",
    "Absolute",
    "RefineQuality",
    "StraightenMidnodes",
    "vecOffset",
    "Laplacian",
    "AlongEdge",
    "AlongDirection",
    "CADFollows",
    "Scale",
  ],
  ElementConvert: [null],
  Deform: [null],
  MirrorCopy: [null],
  DeleteNode: [null],
  FaceImprint: [null],
  AdjustOrientation: [null],
  OneNode: [null],
  SeparateNodes: [null],
  RefineQuality: [null],
  Import: [null],
  RemoveSolidMesh: [null],
  MeshEditCMPMeshCopy: [null],
  MeshEditMorphingRibThickness: [null],
  MergeNodes: [null],
  MeshCopy: [null],
  RibThickness: [null],
  ChangePattern: [null],
  SurfaceMesh: [null],
  SolidMesh: [null],
  CADProjection: ["Part", "Face", "FaceToFace", "NodeToFace", "NodeToEdge"],
  LocalMeshing: ["FilletMapping", "SelectFillet", "FilletMapMeshing"],
  LocalSetting: ["SearchTargetFaces"],
  Templates: ["TemplateCopy"],
  BarMeshing: [null],
  GridMesh: [null],
  SolidMeshing: [null],
  SurfaceMeshing: [null],
  SetAttib: [null],
  LocalRemesh: ["Solid", "Surfase"],
  LocalSettings: ["Edge", "Face", "FaceElement", "Model", "Part", "Points"],
  AdjustThickness: [null],
  FaceCross: [null],
  CreateThickProps: [null],
  FindMidPlane: [null],
  ExtendFace: ["CylinderFace", "PlanarFace"],
  Manual: ["vecOffset", "MidByPair"],
  AddItems: ["Edge", "Face"],
  ACModelCreationTools: ["MeshedFace"],
  ClearanceElement: ["Connect", "Edit"],
  CreateEdge: ["PerpendicularLineToEdge"],
  CreateEdgeClassic: ["ProjectLine"],
  CopyMeshCount: [null],
  SpecialModeling: ["Rod"],
  CreateWeld: ["Auto"],
  DefineSequence: ["Single"],
  MeshingPass: [null],
  Prop3DWeldBead: [null],
  NSModeling_Close_Hole: [null],
  ImportResults: [
    "ImportOp2Mesh",
    "NastranOp2PostJob",
    "ImportTsdbMesh",
    "HDF5Mesh",
    "ADVC",
    "ADVC2PostJob",
    "NastranHDF5",
  ],
  ElemRelatedInfo: ["Shell", "Conn", "Rod", "Beam", "Bar", "Gap", "Bush"],
  Section: [
    "Import",
    "SectionDeleteMulti",
    "Modify_General",
    "Modify_Library",
    "Modify_Sketcher",
    "Export",
    "Delete",
    "Add_General",
    "Add_Library",
    "Add_Sketcher",
    null,
  ],
  Cohesive: [null],
  Gasket: [null],
  Shell: [null],
  PropertyTable: [null],
  Beam: [null],
  Rod: [null],
  Property1DBeamSimple: [null],
  Solid: [null],
  Section1D: [null],
  Composite: [null],
  BAR: [null],
  ThicknessDistribution: [null],
  RigidBody: [null],
  DropTest: ["CalcTimestep", "UpdateFloor", "DropRotation", null],
  CADImport: [null],
  AutoSweepClosedLoopShaped: [null],
  Assembly: ["CreateWeld", "ContactSurface"],
  MeshEdit: ["FilletMapping"],
  AlignMidNode: [null],
  Connection: ["RRod"],
  MeshQuality: ["MeshQualityCheck", "Manual"],
  Muffler: ["ProjectLineForWeld"],
  ZGeometryTest: ["IntersectionCheck", "ShellAssy"],
  FindFeatureFillet: [null],
  FindFacesInPart: [null],
  CreateElementForWelding: [null],
  Connections: ["Contact", "Spring", "RBE3", "Mass", null],
  Coordinates: [
    "CylinderFace",
    "ThreeNode",
    "Align",
    "vecOffset",
    "Rotate",
    "AttachCircle",
    "AttachNode",
    "Face",
  ],
  Group: ["CreateGroup", "DeleteGroupEntity", null],
  ImprintEdges: ["Line", "ClosedLine", "ClosedLine2"],
  ElementCS: [null],
  Measure: ["Angle", "Distance", "Mass", "Radius", "Volume", "Area"],
  Undo: [null],
  Redo: [null],
  BySelection: ["SelectionOrder", "Position", "OriginalID"],
  TotalLoad: ["LBC", "Model", "Node", "Part", "Face"],
  NodeCS: [null],
  NodeCSGroup: [null],
  DisplacementCS: [null],
  GroupByDCS: [null],
  Renumber: [null],
  RenumberByConnection: [null],
  RenumberByFile: [null],
  ModelInfo: [null],
};

export const root3 = [
  "Method1",
  "Convex",
  "DynamicStep",
  "TransientStep",
  "DynamicCoupledTDExplicitStep",
  "CoupledTDStep",
  "DynamicExplicitStep",
  "ModalStep",
  "StaticRiskStep",
  "SteadyStateStep",
  "ExportBdf",
  "Run",
  "CreateEdat",
  "Abaqus",
  "AbaqusSteadyStateStep",
  "AbaqusStaticRiskStep",
  "HeadTransferSteady",
  "LinearStatic",
  "NormalModes",
  "Harmonic",
  "Steady",
  "ModalTransientResponse",
  "LinearBuckling",
  "Transient",
  "SteadyState",
  "ModalFrequencyResponse",
  "Job",
  "ExportDynamisBdf",
  "LinearBucking",
  "NonlinearStatic",
  "NonlinearFrequency",
  "TransientHeatTransfer",
  "SteadyStateHeatTransfer",
  "MakeProcess",
  "Structure",
  "HeatTransfer",
  "AllSharedNodes",
  "Shell",
  "Solid",
  "AddToReference",
  "Suppress",
  "UnSuppress",
  "RestoreOriginalPart",
  "Rename",
  "ChangeEntityColor",
  "AddSubAssembly",
  "ChangeBodyColor",
  "ChangeMeshLineColor",
  "Constant",
  "SurfaceMapping",
  "Acceleration",
  "Velocity",
  "Displacement",
  "SurfaceFlux",
  "ConcentrateFlux",
  "InitialStress",
  "WholeMapping",
  "ADVC",
  "NastranPunch",
  "PropertiesCopyTranslate",
  "PropertiesCopyRotate",
  "PropertiesCopyMirror",
  "ConnectionCopyTranslate",
  "ConnectionCopyRotate",
  "ConnectionCopyMirror",
  "GroupCopyTranslate",
  "GroupCopyRotate",
  "GroupCopyMirror",
  "LBCCopyTranslate",
  "LBCCopyRotate",
  "LBCCopyMirror",
  "SurfaceLoads",
  "By2Nodes",
  "General",
  "Quadratic",
  "FunctionLoadToCylinder_Sine",
  "SerfaceMapping",
  "Hydrostatic",
  "SubmodelForcedFlux",
  "ForcedTempertature",
  "ForcedDisplacement",
  "ADVCFile",
  "LbcInitialTemperature",
  "CentrifugalForce",
  "Gravity",
  "FunctionLoadCylinder",
  "NonlinearForce",
  "ForceNormalDirection",
  "FunctionLoadToCylinder_Quadratic",
  "InitialAngularVelocity",
  "RotationAngle",
  "Advc",
  "Edge",
  "Face",
  "Ansys",
  "MSCNastran",
  "NXNastran",
  "TSSolver",
  "TSSS",
  "CheckPattern",
  "ExportCheckReport",
  "TwoNodes",
  "TwoEdges",
  "TwoFaces",
  "Equation",
  "RBar",
  "RBE2",
  "RBE3",
  "Damper",
  "Bush",
  "Spring",
  "Moment",
  "TemperatureLoad",
  "WeldLine2",
  "Arc",
  "Spline",
  "XXYYOnOnePoint",
  "BySurface",
  "By3Points",
  "StlPart",
  "Part",
  "Vertex",
  "Line",
  "PlanarLine",
  "Circle",
  "PerpendicularLineOfEdge",
  "ExtendLine",
  "ElementEdges",
  "Angle",
  "NodeShortestPath",
  "OffsetLine",
  "Intersection_Line",
  "Projection_Line",
  "SplineFreeEdges",
  "ClosedLine",
  "PerpendicularCylinderLine",
  "IntersectionLine",
  "ProjectLine",
  "PerpendicularLineToEdge",
  "FindFeatureFillet",
  "ExtractRefSurface",
  "ExtractSurfaces",
  "CreateFaceByElem",
  "FourEdges",
  "FromMesh",
  "CreateFaceFromEdges",
  "CreateSmoothFace",
  "Edges",
  "Elements",
  "DelCircChamfer",
  "Fillet",
  "Faces",
  "TinyFacesMerge",
  "CBarParts",
  "Parts",
  "PartFaces",
  "Cube",
  "Wedge",
  "Sphere",
  "Torus",
  "Elems",
  "Cylinder",
  "Tube",
  "Trapezoid",
  "Cone",
  "Rotation",
  "Scaling",
  "Mirror",
  "Position",
  "Translation",
  "MatingFace",
  "CylinderFace",
  "PropertyGroup",
  "DeleteGroup",
  "CopyGroup",
  "AddSupGroup",
  "CreateMatGroup",
  "Circular",
  "FaceToFace",
  "Layer",
  "Linear",
  "Curve",
  "FromMidPlane",
  "Elysium",
  "Spatial",
  "Parasolid",
  "STL",
  "VRML",
  "ProECreoDirect",
  "ADVCADX",
  "AnsysDat",
  "NastranBdf",
  "AbaqusINP",
  "LSDYNA",
  "Universal",
  "MergeFaces",
  "SelectAllParts",
  "AssociatedPick",
  "FlipElement",
  "SolidElement",
  "SurfaceElement",
  "Element",
  "CloseGap",
  "MergeElement",
  "SplitElement",
  "Equivalence",
  "DeleteElement",
  "Split",
  "Swap",
  "Collapse",
  "CreateElement",
  "RemeshElement",
  "DeleteNode",
  "CreateHex",
  "CreatePenta",
  "CreateTetra",
  "Tri",
  "Hex",
  "Penta",
  "Tet",
  "Tri3",
  "Quad4",
  "CircleCenter",
  "SphereCenter",
  "Absolute",
  "Import",
  "Point",
  "Between2Nodes",
  "Between3Nodes",
  "ProjectToPlane",
  "CreateNodeNodeOffset",
  "CenterOfCylinder",
  "CenterOfSphere",
  "vecOffset",
  "CenterOfGravity",
  "ProjectToLine",
  "IntersectionNode",
  "ProjectToPlaneElem",
  "Equalize",
  "StraightenMidNodes",
  "NormalOffset",
  "CoincidentNodes",
  "AlongCylinder",
  "ProjectToPlane_3Nodes",
  "MoveNodeOffset",
  "RefineQuality",
  "StraightenMidnodes",
  "Laplacian",
  "AlongEdge",
  "AlongDirection",
  "CADFollows",
  "Scale",
  "NodeToFace",
  "NodeToEdge",
  "FilletMapping",
  "SelectFillet",
  "SearchTargetFaces",
  "TemplateCopy",
  "Surfase",
  "FaceElement",
  "Model",
  "Points",
  "Nodes",
  "PlanarFace",
  "FaceExtendtoFace",
  "FaceExtendToIntersection",
  "EdgesToEdges",
  "MidByPair",
  "MeshedFace",
  "Connect",
  "Edit",
  "Rod",
  "Auto",
  "Single",
  "FilletMapMeshing",
  "ImportOp2Mesh",
  "NastranOp2PostJob",
  "ImportTsdbMesh",
  "HDF5Mesh",
  "ADVC2PostJob",
  "NastranHDF5",
  "Conn",
  "Beam",
  "Bar",
  "Gap",
  "add",
  "modify",
  "delete",
  "SectionDeleteMulti",
  "Modify_General",
  "Modify_Library",
  "Modify_Sketcher",
  "Export",
  "Delete",
  "Add_General",
  "Add_Library",
  "Add_Sketcher",
  "CalcTimestep",
  "UpdateFloor",
  "DropRotation",
  "CreateWeld",
  "ContactSurface",
  "RRod",
  "MeshQualityCheck",
  "ProjectLineForWeld",
  "IntersectionCheck",
  "ShellAssy",
  "Contact",
  "Mass",
  "ThreeNode",
  "Align",
  "Rotate",
  "AttachCircle",
  "AttachNode",
  "CreateGroup",
  "DeleteGroupEntity",
  "ClosedLine2",
  "Distance",
  "Radius",
  "Volume",
  "Manual",
  "SelectionOrder",
  "OriginalID",
  "LBC",
  "Node",
  "Area",
];

export const map34 = {
  undefined: [null],
  Method1: [null],
  Convex: [null],
  DynamicStep: [null],
  TransientStep: [null],
  DynamicCoupledTDExplicitStep: [null],
  CoupledTDStep: [null],
  DynamicExplicitStep: [null],
  ModalStep: [null],
  StaticRiskStep: [null],
  SteadyStateStep: [null],
  ExportBdf: [null],
  Run: [null],
  CreateEdat: [null],
  Abaqus: [
    null,
    "ContactTable",
    "ManualGroup",
    "ManualFace",
    "ContactGroupByMatrix",
    "ContactShareFace",
  ],
  AbaqusSteadyStateStep: [null],
  AbaqusStaticRiskStep: [null],
  HeadTransferSteady: [null],
  LinearStatic: [null],
  NormalModes: [null],
  Harmonic: [null],
  Steady: [null],
  ModalTransientResponse: [null],
  LinearBuckling: [null],
  Transient: [null],
  SteadyState: [null],
  ModalFrequencyResponse: [null],
  Job: [null],
  ExportDynamisBdf: [null],
  LinearBucking: [null],
  NonlinearStatic: [null],
  NonlinearFrequency: [null],
  TransientHeatTransfer: [null],
  SteadyStateHeatTransfer: [null],
  MakeProcess: [
    "Static",
    "Creep",
    "Dynamic",
    "EigenValue",
    "DynamicExplicit",
    "ModalFreqResp",
    "ResponseSpectrum",
    "SteadyState",
    "Transient",
    "Fatigue",
    "RandomResponse",
  ],
  Structure: [null],
  HeatTransfer: [null],
  AllSharedNodes: [null],
  Shell: [null],
  Solid: [null],
  AddToReference: [null],
  Suppress: [null],
  UnSuppress: [null],
  RestoreOriginalPart: [null],
  Rename: [null],
  ChangeEntityColor: [null],
  AddSubAssembly: [null],
  ChangeBodyColor: [null],
  ChangeMeshLineColor: [null],
  Constant: [null],
  SurfaceMapping: [null],
  Acceleration: [null],
  Velocity: [null],
  Displacement: [null],
  SurfaceFlux: [null],
  ConcentrateFlux: [null],
  InitialStress: [null],
  WholeMapping: [null],
  ADVC: [
    null,
    "ContactClearance",
    "ManualGroup",
    "ManualFace",
    "Contact",
    "ContactShareFace",
    "ContactTable",
    "ContactGroupByMatrix",
  ],
  NastranPunch: [null],
  PropertiesCopyTranslate: [null],
  PropertiesCopyRotate: [null],
  PropertiesCopyMirror: [null],
  ConnectionCopyTranslate: [null],
  ConnectionCopyRotate: [null],
  ConnectionCopyMirror: [null],
  GroupCopyTranslate: [null],
  GroupCopyRotate: [null],
  GroupCopyMirror: [null],
  LBCCopyTranslate: [null],
  LBCCopyRotate: [null],
  LBCCopyMirror: [null],
  SurfaceLoads: [null],
  By2Nodes: [null],
  General: [
    null,
    "NodeToNode",
    "NodeToEdges",
    "NodeToFaces",
    "TwoEdges",
    "FacesToFaces",
    "NodesToNodes",
    "TwoFaces",
    "NodeToAny",
    "NodesWithTolerance",
  ],
  Quadratic: [null],
  FunctionLoadToCylinder_Sine: [null],
  SerfaceMapping: [null],
  Hydrostatic: [null],
  SubmodelForcedFlux: [null],
  ForcedTempertature: [null],
  ForcedDisplacement: [null],
  ADVCFile: [null],
  LbcInitialTemperature: [null],
  CentrifugalForce: ["CoordinateSystems", "TwoPositions"],
  Gravity: [null],
  FunctionLoadCylinder: ["Quadratic", "Sine", "Vector"],
  NonlinearForce: ["NOLIN3", "NOLIN4", "NOLIN1"],
  ForceNormalDirection: [null],
  FunctionLoadToCylinder_Quadratic: [null],
  InitialAngularVelocity: ["Abaqus", "General"],
  RotationAngle: [null],
  Advc: [null],
  Edge: [
    "TypeC",
    "TypeB",
    "TypeD",
    "TypeA",
    null,
    "ProjectEdgeToFace",
    "FaceTwoFace",
  ],
  Face: ["TypeC", "TypeB", "TypeA", null, "EFExtendFreeEdge", "EFProject"],
  Ansys: [
    "ManualGroup",
    "ManualFace",
    "ContactGroupByMatrix",
    "ContactShareFace",
    "ContactTable",
    null,
  ],
  MSCNastran: [
    "ManualGroup",
    "ContactGroupByMatrix",
    "ManualFace",
    "ContactShareFace",
    "ContactTable",
  ],
  NXNastran: [
    "ManualFace",
    "ContactShareFace",
    "ContactTable",
    "ManualGroup",
    "ContactGroupByMatrix",
    null,
  ],
  TSSolver: ["ManualFace", "Auto", "ManualGroup"],
  TSSS: ["ManualFace", "ManualGroup", "ContactTable"],
  CheckPattern: [null],
  ExportCheckReport: [null],
  TwoNodes: [null],
  TwoEdges: [null],
  TwoFaces: [null],
  Equation: ["MultiNodes", "TwoFace", "SemiAuto"],
  RBar: ["OneToOne", "OneToMany", "OneToOneNodesWithTolerance", null],
  RBE2: [
    "OneToMany",
    "OneToOne",
    "OneToOneNodesWithTolerance",
    "ToCenter",
    "ToCircleCenter",
    null,
  ],
  RBE3: ["OneToMany", "OneToOne", "ToCenter", "ToCircleCenter", null],
  Damper: ["AnyEntities11DoFS"],
  Bush: [null, "TwoNodes", "AnyEntities", "OnetoOne"],
  Spring: ["GroundedSpring", "Nodeswithtolerance", "OneToOne", null],
  Moment: [null],
  TemperatureLoad: [null],
  WeldLine2: [null],
  Arc: [null],
  Spline: [null],
  XXYYOnOnePoint: [null],
  BySurface: [null],
  By3Points: [null],
  StlPart: [null],
  Part: [null],
  Vertex: [null],
  Line: [null],
  PlanarLine: [null],
  Circle: [null],
  PerpendicularLineOfEdge: [null],
  ExtendLine: [null],
  ElementEdges: [null],
  Angle: [
    null,
    "ProjectedNode",
    "TwoNodesAxis",
    "By2Axis",
    "ThreeNodes",
    "TwoElemEdges",
    "TwoAxis",
    "TwoEdges",
  ],
  NodeShortestPath: [null],
  OffsetLine: [null],
  Intersection_Line: [null],
  Projection_Line: [null],
  SplineFreeEdges: [null],
  ClosedLine: [null],
  PerpendicularCylinderLine: [null],
  IntersectionLine: [null],
  ProjectLine: [null],
  PerpendicularLineToEdge: [null],
  FindFeatureFillet: [null],
  ExtractRefSurface: [null],
  ExtractSurfaces: [null],
  CreateFaceByElem: [null],
  FourEdges: [null],
  FromMesh: [null],
  CreateFaceFromEdges: [null],
  CreateSmoothFace: [null],
  Edges: [null],
  Elements: [null],
  DelCircChamfer: [null],
  Fillet: [null],
  Faces: [null],
  TinyFacesMerge: [null],
  CBarParts: [null],
  Parts: [null],
  PartFaces: [null],
  Cube: [null],
  Wedge: [null],
  Sphere: [null],
  Torus: [null],
  Elems: [null],
  Cylinder: [null],
  Tube: [null],
  Trapezoid: [null],
  Cone: [null],
  Rotation: [null],
  Scaling: [null],
  Mirror: [null],
  Position: [null],
  Translation: [null],
  MatingFace: [null],
  CylinderFace: [null],
  PropertyGroup: [null],
  DeleteGroup: [null],
  CopyGroup: [null],
  AddSupGroup: [null],
  CreateMatGroup: [null],
  Circular: [null],
  FaceToFace: [null],
  Layer: [null],
  Linear: [null],
  Curve: [null],
  FromMidPlane: [null],
  Elysium: [null],
  Spatial: [null],
  Parasolid: [null],
  STL: [null],
  VRML: [null],
  ProECreoDirect: [null],
  ADVCADX: [null],
  AnsysDat: [null],
  NastranBdf: [null],
  AbaqusINP: [null],
  LSDYNA: [null],
  Universal: [null],
  MergeFaces: [null],
  SelectAllParts: [null],
  AssociatedPick: [null],
  FlipElement: [null],
  SolidElement: [null],
  SurfaceElement: [null],
  Element: ["SurfaceElement"],
  CloseGap: [null],
  MergeElement: ["TwoQuadsToQuad", "TwoTrisToQuad"],
  SplitElement: [
    "QuadTo4Quads",
    "QuadToTrans4Quads",
    "QuadToTrans3Quads",
    "QuadTo2Quads1Tri",
    "QuadTo3Tris",
    "QuadTo2Quads",
    "QuadTo2Tris",
    "QuadToQuadTri",
    "QuadTo4Tris",
    null,
  ],
  Equivalence: [null],
  DeleteElement: [null],
  Split: [null],
  Swap: [null],
  Collapse: [null, "CenterFaceCollapse", "HalfEdgeCollapse", "EdgeCollapse"],
  CreateElement: [null],
  RemeshElement: [null],
  DeleteNode: [null],
  CreateHex: [null],
  CreatePenta: [null],
  CreateTetra: [null],
  Tri: [null],
  Hex: [null],
  Penta: [null],
  Tet: [null],
  Tri3: [null],
  Quad4: [null],
  CircleCenter: [null],
  SphereCenter: [null],
  Absolute: [null],
  Import: [null],
  Point: [null],
  Between2Nodes: [null],
  Between3Nodes: [null],
  ProjectToPlane: [null],
  CreateNodeNodeOffset: [null],
  CenterOfCylinder: [null],
  CenterOfSphere: [null],
  vecOffset: [null],
  CenterOfGravity: [null],
  ProjectToLine: [null],
  IntersectionNode: [null],
  ProjectToPlaneElem: [null],
  Equalize: [null],
  StraightenMidNodes: [null],
  NormalOffset: [null],
  CoincidentNodes: [null],
  AlongCylinder: [null],
  ProjectToPlane_3Nodes: [null],
  MoveNodeOffset: [null],
  RefineQuality: [null],
  StraightenMidnodes: [null],
  Laplacian: [null],
  AlongEdge: [null],
  AlongDirection: [null],
  CADFollows: [null],
  Scale: [null],
  NodeToFace: [null],
  NodeToEdge: [null],
  FilletMapping: [null],
  SelectFillet: [null],
  SearchTargetFaces: [null],
  TemplateCopy: [null],
  Surfase: [null],
  FaceElement: [null],
  Model: [null],
  Points: [null],
  Nodes: [null],
  PlanarFace: [null],
  FaceExtendtoFace: [null],
  FaceExtendToIntersection: [null],
  EdgesToEdges: [null],
  MidByPair: [null],
  MeshedFace: [null],
  Connect: [null],
  Edit: [null],
  Rod: ["Rod", null],
  Auto: [null],
  Single: [null],
  FilletMapMeshing: [null],
  ImportOp2Mesh: [null],
  NastranOp2PostJob: [null],
  ImportTsdbMesh: [null],
  HDF5Mesh: [null],
  ADVC2PostJob: [null],
  NastranHDF5: [null],
  Conn: [null],
  Beam: [null],
  Bar: [null],
  Gap: [null],
  add: [null],
  modify: [null],
  delete: [null],
  SectionDeleteMulti: [null],
  Modify_General: [null],
  Modify_Library: [null],
  Modify_Sketcher: [null],
  Export: [null],
  Delete: [null],
  Add_General: [null],
  Add_Library: [null],
  Add_Sketcher: [null],
  CalcTimestep: [null],
  UpdateFloor: [null],
  DropRotation: [null],
  CreateWeld: [null],
  ContactSurface: [null],
  RRod: [null],
  MeshQualityCheck: [null],
  ProjectLineForWeld: [null],
  IntersectionCheck: [null],
  ShellAssy: [null],
  Contact: [null],
  Mass: [null, "ByMaterial", "Property", "Material"],
  ThreeNode: [null],
  Align: [null],
  Rotate: [null],
  AttachCircle: [null],
  AttachNode: [null],
  CreateGroup: [null],
  DeleteGroupEntity: [null],
  ClosedLine2: [null],
  Distance: [
    "Edge",
    "EdgeNode",
    "TwoPoints",
    "LineNode",
    "Plane3NodesToNode",
    "TwoEdges",
    "PlaneElemToNode",
    "TwoNodes",
    "FaceNode",
  ],
  Radius: ["ByThreeNodes", "MeasureRadiusBy3Nodes", "Edge", "ThreeNodes"],
  Volume: [null],
  Manual: ["CleanTetCollapse", "CleaningVolumeMesh"],
  SelectionOrder: [null],
  OriginalID: [null],
  LBC: [null],
  Node: [null],
  Area: ["Element", "Face", "Body"],
};

export const root4 = [
  "Static",
  "Creep",
  "Dynamic",
  "EigenValue",
  "DynamicExplicit",
  "ModalFreqResp",
  "ResponseSpectrum",
  "SteadyState",
  "Transient",
  "Fatigue",
  "RandomResponse",
  "CoordinateSystems",
  "TwoPositions",
  "Quadratic",
  "Sine",
  "Vector",
  "NOLIN3",
  "NOLIN4",
  "NOLIN1",
  "Abaqus",
  "General",
  "TypeC",
  "TypeB",
  "TypeD",
  "TypeA",
  "ContactTable",
  "ManualGroup",
  "ManualFace",
  "ContactGroupByMatrix",
  "ContactShareFace",
  "ContactClearance",
  "Contact",
  "Auto",
  "MultiNodes",
  "TwoFace",
  "SemiAuto",
  "NodeToNode",
  "NodeToEdges",
  "NodeToFaces",
  "TwoEdges",
  "FacesToFaces",
  "NodesToNodes",
  "TwoFaces",
  "NodeToAny",
  "NodesWithTolerance",
  "OneToOne",
  "OneToMany",
  "OneToOneNodesWithTolerance",
  "ToCenter",
  "ToCircleCenter",
  "AnyEntities11DoFS",
  "TwoNodes",
  "AnyEntities",
  "OnetoOne",
  "GroundedSpring",
  "Nodeswithtolerance",
  "SurfaceElement",
  "TwoQuadsToQuad",
  "TwoTrisToQuad",
  "QuadTo4Quads",
  "QuadToTrans4Quads",
  "QuadToTrans3Quads",
  "QuadTo2Quads1Tri",
  "QuadTo3Tris",
  "QuadTo2Quads",
  "QuadTo2Tris",
  "QuadToQuadTri",
  "QuadTo4Tris",
  "CenterFaceCollapse",
  "HalfEdgeCollapse",
  "EdgeCollapse",
  "ProjectEdgeToFace",
  "FaceTwoFace",
  "EFExtendFreeEdge",
  "EFProject",
  "Rod",
  "ProjectedNode",
  "TwoNodesAxis",
  "By2Axis",
  "Edge",
  "EdgeNode",
  "TwoPoints",
  "LineNode",
  "Plane3NodesToNode",
  "PlaneElemToNode",
  "FaceNode",
  "ByMaterial",
  "ByThreeNodes",
  "MeasureRadiusBy3Nodes",
  "CleanTetCollapse",
  "CleaningVolumeMesh",
  "ThreeNodes",
  "TwoElemEdges",
  "TwoAxis",
  "Element",
  "Face",
  "Body",
  "Property",
  "Material",
];

export const map45 = {
  undefined: [null],
  Static: [null],
  Creep: [null],
  Dynamic: [null],
  EigenValue: [null],
  DynamicExplicit: [null],
  ModalFreqResp: [null],
  ResponseSpectrum: [null],
  SteadyState: [null],
  Transient: [null],
  Fatigue: [null],
  RandomResponse: [null],
  CoordinateSystems: [null],
  TwoPositions: [null],
  Quadratic: [null],
  Sine: [null],
  Vector: [null],
  NOLIN3: [null],
  NOLIN4: [null],
  NOLIN1: [null],
  Abaqus: [null],
  General: [null],
  TypeC: [null],
  TypeB: [null],
  TypeD: [null],
  TypeA: [null],
  ContactTable: [null],
  ManualGroup: [null],
  ManualFace: [null],
  ContactGroupByMatrix: [null],
  ContactShareFace: [null],
  ContactClearance: [null],
  Contact: [null],
  Auto: [null],
  MultiNodes: [null],
  TwoFace: [null],
  SemiAuto: [null],
  NodeToNode: [null],
  NodeToEdges: [null],
  NodeToFaces: [null],
  TwoEdges: [null],
  FacesToFaces: [null],
  NodesToNodes: [null],
  TwoFaces: [null],
  NodeToAny: [null],
  NodesWithTolerance: [null],
  OneToOne: [null, "sameDoFs", "differentDoFs"],
  OneToMany: [null],
  OneToOneNodesWithTolerance: [null],
  ToCenter: [null],
  ToCircleCenter: [null],
  AnyEntities11DoFS: [null],
  TwoNodes: [null],
  AnyEntities: [null],
  OnetoOne: [null],
  GroundedSpring: [null],
  Nodeswithtolerance: ["sameDoFs", "differentDoFs"],
  SurfaceElement: [null],
  TwoQuadsToQuad: [null],
  TwoTrisToQuad: [null],
  QuadTo4Quads: [null],
  QuadToTrans4Quads: [null],
  QuadToTrans3Quads: [null],
  QuadTo2Quads1Tri: [null],
  QuadTo3Tris: [null],
  QuadTo2Quads: [null],
  QuadTo2Tris: [null],
  QuadToQuadTri: [null],
  QuadTo4Tris: [null],
  CenterFaceCollapse: [null],
  HalfEdgeCollapse: [null],
  EdgeCollapse: [null],
  ProjectEdgeToFace: [null],
  FaceTwoFace: [null],
  EFExtendFreeEdge: [null],
  EFProject: [null],
  Rod: [null],
  ProjectedNode: [null],
  TwoNodesAxis: [null],
  By2Axis: [null],
  Edge: [null],
  EdgeNode: [null],
  TwoPoints: [null],
  LineNode: [null],
  Plane3NodesToNode: [null],
  PlaneElemToNode: [null],
  FaceNode: [null],
  ByMaterial: [null],
  ByThreeNodes: [null],
  MeasureRadiusBy3Nodes: [null],
  CleanTetCollapse: [null],
  CleaningVolumeMesh: [null],
  ThreeNodes: [null],
  TwoElemEdges: [null],
  TwoAxis: [null],
  Element: [null],
  Face: [null],
  Body: [null],
  Property: [null],
  Material: [null],
};
